kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
zfs_load="YES"
fusefs_load="YES"
hw.vmm.amdvi.enable=1
acpi_load="YES"
acpi_video_load="YES"
acpi_ibm_load="YES"
coretemp_load="YES"
drm.i915.enable_rc6="7"
drm.i915.semaphores="1"
drm.i915.enable_fbc="1"
drm.i915.enable_psr="1"
