clear_tmp_enable="YES"
hostname="dkolak"
keymap="tr.kbd"
# wlans_iwlwifi0="wlan0"
# ifconfig_wlan0="WPA  DHCP"
# create_args_wlan0="country TR regdomain ETSI"
ifconfig_wifibox0="inet 10.0.0.2 netmask 255.255.255.0"
sshd_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"
acpi_enable="YES"
powerd_enable="YES"
powerd_flags="-a hiadaptive -b adaptive -n adaptive -i 85 -r 60 -p 100"
moused_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
zfs_enable="YES"
kld_list="i915kms"
linux_enable="YES"
dbus_enable="YES"
ifconfig_em0="DHCP"
wifibox_enable="YES"
devmatch_enable="YES"
devmatch_blocklist="if_iwm if_iwlwifi if_iwx"
background_dhclient_wifibox0="YES"
defaultroute_delay="0"
ifconfig_ue0="DHCP"
defaultrouter="10.0.0.1"
